---
- hosts: all
  become: true
  tasks:

    - name: apt upgrade
      apt:
        upgrade: "yes"
        update_cache: "yes"
        cache_valid_time: 3600
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install ripgrep
      package:
        name: 
          - ripgrep
          - unzip


- hosts: physical
  tasks:

    - name: test
      command: sensors

