---
- hosts: prox
  gather_facts: false   # some hosts might not be started until after this
  roles:
    - role: start_prox
      name: "Start VMs & CTs on Proxmox"

# - hosts: all
#   become: true
#   roles:
#     - update
#     - utils
#
# - hosts: terminal_users
#   become: true
#   roles:
#     - nvim

- hosts: media-box
  become: true
  roles:
    - docker
