$ANSIBLE_VAULT;1.1;AES256
30326133663532323538366430373266323062363361633962313961363835373032396231643039
3365376135373537366337303266373965396437663634640a623734613632386630386332323562
63316431373564303835656431326334346437373036653331663334373237633739303263376363
6265653261663538310a353838653338373734396162643439626363373061636136613132653865
33623565373538303531396262363536316632633365646266363234333232636166643231653036
3461303936663431363633663534323762313731326338616232
