- name: Update & upgrade packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 3600
  when: 
    - ansible_distribution in ["Debian", "Ubuntu"] 
    - inventory_hostname != "prox-server"

# for proxmox we need to do apt dist-upgrade to ensure
# dependencies are always installed 
# - name: Update & dist upgrade for Prox
#   apt:
#     update_cache: yes
#     upgrade: dist
#     autoremove: yes
#     autoclean: yes
#   when: inventory_hostname == "prox-server"
