$ANSIBLE_VAULT;1.1;AES256
30626332363366626231333536336465336530326231396666306638633930323666316636663433
3633393336323330656561623230363937346565656135620a386165386236373562313932333564
32366530383230363361646531386163326332633634666235386332643932383239366635383333
6637343834303233350a326235333964656563313164303234353265623263626162636132363232
62383762666438373935666332313534643265303762323864336661623533356230
